apiVersion: v1
kind: Secret
metadata:
  name: habit-tracker-secrets
  namespace: default
  labels:
    app: habit-tracker
    environment: production
    secret-rotation: enabled
    component: configuration
    managed-by: kubernetes
  annotations:
    last-rotated: "2024-01-01T00:00:00Z"  # Updated automatically by rotation system
    rotation-schedule: "30d"
    backup-enabled: "true"
    encryption.kubernetes.io/provider: "aescbc"
    vault.hashicorp.com/agent-inject: "true"
    checksum/secrets: "${SECRETS_CHECKSUM}"  # Automatically updated on changes
    security.policy/audit-level: "strict"

type: Opaque

# Database Credentials
data:
  # PostgreSQL credentials
  DB_USER: "${BASE64_DB_USER}"  # Base64 encoded production database username
  DB_PASSWORD: "${BASE64_DB_PASSWORD}"  # Base64 encoded production database password
  DB_CONNECTION_STRING: "${BASE64_DB_CONNECTION_STRING}"  # Base64 encoded connection string with SSL params
  DB_BACKUP_ENCRYPTION_KEY: "${BASE64_DB_BACKUP_KEY}"  # Base64 encoded AES-256 backup encryption key
  
  # Redis credentials
  REDIS_PASSWORD: "${BASE64_REDIS_PASSWORD}"  # Base64 encoded Redis auth password
  REDIS_CLUSTER_URLS: "${BASE64_REDIS_URLS}"  # Base64 encoded Redis cluster endpoints

# Authentication Secrets  
  # Auth0 credentials
  AUTH0_CLIENT_SECRET: "${BASE64_AUTH0_SECRET}"  # Base64 encoded Auth0 client secret
  AUTH0_API_KEY: "${BASE64_AUTH0_API_KEY}"  # Base64 encoded Auth0 Management API key
  
  # JWT and session encryption
  JWT_SECRET: "${BASE64_JWT_SECRET}"  # Base64 encoded JWT signing key (min 256-bit)
  SESSION_ENCRYPTION_KEY: "${BASE64_SESSION_KEY}"  # Base64 encoded session encryption key
  MFA_ENCRYPTION_KEY: "${BASE64_MFA_KEY}"  # Base64 encoded MFA secret encryption key

# External Service Credentials
  # Email and monitoring
  SENDGRID_API_KEY: "${BASE64_SENDGRID_KEY}"  # Base64 encoded SendGrid API key
  MONITORING_API_TOKEN: "${BASE64_MONITORING_TOKEN}"  # Base64 encoded monitoring service token
  ANALYTICS_SECRET_KEY: "${BASE64_ANALYTICS_KEY}"  # Base64 encoded analytics API key

# TLS Certificates
  # Server certificates
  TLS_CERT: "${BASE64_TLS_CERT}"  # Base64 encoded TLS certificate
  TLS_KEY: "${BASE64_TLS_KEY}"  # Base64 encoded TLS private key
  CA_CERT: "${BASE64_CA_CERT}"  # Base64 encoded CA certificate

# Backup encryption keys
  BACKUP_ENCRYPTION_KEY: "${BASE64_BACKUP_KEY}"  # Base64 encoded backup encryption key
  RECOVERY_KEY: "${BASE64_RECOVERY_KEY}"  # Base64 encoded disaster recovery key

# Additional security configurations
  SECURITY_SALT: "${BASE64_SECURITY_SALT}"  # Base64 encoded security salt
  ENCRYPTION_CONFIG: "${BASE64_ENCRYPTION_CONFIG}"  # Base64 encoded encryption settings