# Grafana Helm Values Configuration
# Version: grafana 9.x
# Kubernetes: 1.24.x

grafana:
  enabled: true
  
  # Image configuration
  image:
    repository: grafana/grafana
    tag: "9.5.1"  # Specific version for production stability
    pullPolicy: IfNotPresent
  
  # Deployment configuration
  replicas: 1
  
  # Resource allocation
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  # Persistence configuration
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    annotations: {}
  
  # Security context for non-root execution
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  
  # Health check probes
  livenessProbe:
    enabled: true
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 10
    
  readinessProbe:
    enabled: true
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 30
    timeoutSeconds: 30
    failureThreshold: 10
  
  # Service configuration
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "3000"
  
  # Ingress configuration
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    hosts:
      - host: grafana.habit-tracker.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.habit-tracker.com
  
  # Data sources configuration
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true
          
        - name: Elasticsearch
          type: elasticsearch
          url: http://elasticsearch-master.monitoring.svc.cluster.local:9200
          access: proxy
          database: "[logs-]YYYY.MM.DD"
          
        - name: Jaeger
          type: jaeger
          url: http://jaeger-query.monitoring.svc.cluster.local:16686
          access: proxy
  
  # Dashboard providers configuration
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards
  
  # Dashboards configuration
  dashboards:
    default:
      services-dashboard:
        json: |
          {
            "title": "Services Dashboard",
            "uid": "services",
            "panels": [
              {
                "title": "API Response Times",
                "type": "graph",
                "gridPos": {"x": 0, "y": 0, "w": 12, "h": 8}
              },
              {
                "title": "Database Metrics",
                "type": "graph",
                "gridPos": {"x": 12, "y": 0, "w": 12, "h": 8}
              }
            ]
          }
      system-dashboard:
        json: |
          {
            "title": "System Metrics",
            "uid": "system",
            "panels": [
              {
                "title": "CPU Usage",
                "type": "graph",
                "gridPos": {"x": 0, "y": 0, "w": 12, "h": 8}
              },
              {
                "title": "Memory Usage",
                "type": "graph",
                "gridPos": {"x": 12, "y": 0, "w": 12, "h": 8}
              }
            ]
          }
  
  # Additional Grafana configuration
  grafana.ini:
    server:
      root_url: https://grafana.habit-tracker.com
      
    security:
      allow_embedding: true
      cookie_secure: true
      cookie_samesite: strict
      
    auth:
      disable_login_form: false
      oauth_auto_login: false
      
    users:
      allow_sign_up: false
      auto_assign_org_role: Viewer
      
    metrics:
      enabled: true
      
    alerting:
      enabled: true
      
    unified_alerting:
      enabled: true